#!/bin/sh -x

# Usage:  postmkvirtualenv [PACKAGE ...]
#
# PACKAGE is the name of a file or folder in
# e.g. /usr/lib64/python2.7/site-packages (if not specified it defaults to
# commonly needed system packages like PyQt4, dbus and VTK)
virtualenv-cherry-pick-system-package()
{
    system_packages_to_symlink=${1:-sip.so dbus _dbus_bindings.so _dbus_qt PyQt4 vtk}
    echo ${system_packages_to_symlink}

    python_version=$(python -c "import sys; print (str(sys.version_info[0])+'.'+str(sys.version_info[1]))")
    system_python=$(which -a python${python_version} | tail -n 1)
    
    get_python_lib_cmd="from distutils.sysconfig import get_python_lib; print (get_python_lib(plat_specific=True))"
    lib_virtualenv_path=$(python -c "${get_python_lib_cmd}")
    lib_system_path=$(${system_python} -c "${get_python_lib_cmd}")
    
    for x in ${system_packages_to_symlink}; do
        ln -snf ${lib_system_path}/${x} ${lib_virtualenv_path}/${x}
    done
}

# Default use case (e.g. when virtualenvwrapper sources this script)
virtualenv-cherry-pick-system-package
